### ISSUE TITLE
Could Not Add The Package In The Xcode

### ISSUE THREAD

**Issue by rahat14** [pusher/pusher-http-swift#47]
I tried to add this package to our application via SPM but failed. Some Error Were thrown. Please Chek Attached File
[https://pasteboard.co/foC1ZP0aazUp.png](image 1)
[https://pasteboard.co/AZPsszb4waxk.png](image 2 )

**Comment by benjamin-tang-pusher** [comment]
Hi, we have some lingering tagging/version stability issues, as a temporary workaround specify this in your package.swift:

```
dependencies: [
        .package(name:"Pusher", url: "https://github.com/pusher/pusher-http-swift.git", revision: "1b2d6e9d41c92485e20bbbc8fabe108edd4cdaee"),
    ],
```
Or if you're using XCode, use when adding the pusher/pusher-http-swift package, select commit in the dropdown and paste the above commit.

Does it resolve after this?

**Comment by benjamin-tang-pusher** [comment]
I will close this for now since this temp workaround should work for now. I the long run we will fix an issue with tweetnacl-swiftwrap dependency (the commit # its currently locked to in the Package.swift is unstable, and SPM doesn't like that).
